# Generated by Django 2.2.4 on 2020-01-12 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_city_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='country',
        ),
    ]
